/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Mountrise (https://sketchfab.com/Mountrise)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/phone-booth-94fca8c5ac9f4974bd4a02e8f571f493
Title: Phone Booth
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Phone(props) {
  const { nodes, materials } = useGLTF('src/public/models/phone/phone.gltf')
  return (
      <group {...props} dispose={null}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group position={[0, 0, 0]}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_3.geometry}
                material={materials['Material.002']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_4.geometry}
                material={materials['Material.004']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_5.geometry}
                material={materials['Material.001']}
            />
          </group>
        </group>
      </group>
  )
}

useGLTF.preload('src/public/models/phone/phone.gltf')
